module.exports = {
  "code": 0,
  "message": "成功请求",
  "data": [{
    "lanmu_id": 0,
    "lanmu_name": "头条",
    "lanmu_order": 0,
    "lanmu_menu": 1,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=0"
  }, {
    "lanmu_id": 32,
    "lanmu_name": "链圈",
    "lanmu_order": 1,
    "lanmu_menu": 1,
    "lanmu_custom": 1,
    "lanmu_json": "/V2/news/list.html?chid=32"
  }, {
    "lanmu_id": 59,
    "lanmu_name": "比特币",
    "lanmu_order": 2,
    "lanmu_menu": 1,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=59"
  }, {
    "lanmu_id": 61,
    "lanmu_name": "以太坊",
    "lanmu_order": 3,
    "lanmu_menu": 1,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=61"
  }, {
    "lanmu_id": 13,
    "lanmu_name": "交易所",
    "lanmu_order": 4,
    "lanmu_menu": 1,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=13"
  }, {
    "lanmu_id": 30,
    "lanmu_name": "挖矿",
    "lanmu_order": 5,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=30"
  }, {
    "lanmu_id": 70,
    "lanmu_name": "热门项目",
    "lanmu_order": 7,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=70"
  }, {
    "lanmu_id": 111,
    "lanmu_name": "底层技术",
    "lanmu_order": 8,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=111"
  }, {
    "lanmu_id": 12,
    "lanmu_name": "P2P",
    "lanmu_order": 9,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=12"
  }, {
    "lanmu_id": 60,
    "lanmu_name": "应用",
    "lanmu_order": 10,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=60"
  }, {
    "lanmu_id": 62,
    "lanmu_name": "讨论",
    "lanmu_order": 11,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=62"
  }, {
    "lanmu_id": 10,
    "lanmu_name": "前景",
    "lanmu_order": 12,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=10"
  }, {
    "lanmu_id": 9,
    "lanmu_name": "加密",
    "lanmu_order": 13,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=9"
  }],
  "updateDime": 1471398874
}
